### ISSUE TITLE
lrmate200id: invalid rotation direction joint 6

### ISSUE THREAD

**Issue by swezap** [ros-industrial/fanuc_experimental#16]
The axis definition of joint 6 in lrmate200id_macro.xacro is wrong so that joint 6 rotates in the wrong direction. It is currently `<axis xyz="1 0 0"/>` but should be `<axis xyz="-1 0 0"/>`.

**Comment by gavanderhoorn** [comment]
Thanks for reporting. I generally check these things rather thoroughly, but it's certainly possible that I slipped up here.

I'll check and fix it if necessary.

**Comment by gavanderhoorn** [comment]
And this is exactly the reason we have this package in the `experimental` repository :).

**Comment by gavanderhoorn** [comment]
You were right. I checked against the manual and inverted the rotation direction of axis 6.

thanks again.
