### ISSUE TITLE
inertial values for fanuc_lrmate200id

### ISSUE THREAD

**Issue by wkentaro** [ros-industrial/fanuc_experimental#22]
I'd like to use fanuc_lrmate200id on gazebo, but it requires setting inertial value on urdf file.
Are there any data sheets for this?

**Comment by gavanderhoorn** [comment]
No. Fanuc (like many other industrial robot manufacturers) considers that kind of information a trade secret (similar to maximum torques, link masses, etc). You won't find it in any datasheet.

Some alternatives:
- [gazebosim.org - Inertial parameters of triangle meshes](http://gazebosim.org/tutorials?tut=inertia&cat=build_robot)
- [URDF link mass inertia properties](http://answers.ros.org/question/39107/urdf-link-mass-inertia-properties/)
- [SolidWorks teacher blog: SolidWorks to Gazebo Robot Simulation](http://blogs.solidworks.com/teacher/2014/05/solidworks-to-gazebo-robot-simulation.html) (and the [linked pdf](http://blogs.solidworks.com/teacher/wp-content/uploads/sites/3/WPI-Robotics-SolidWorks-to-Gazebo.pdf))
- approximations using cylinders, as used in [ur_description](https://github.com/ros-industrial/universal_robot/blob/1ef4d5ba82af5c1dc972f2f1df37a4bc1e6d2b25/ur_description/urdf/ur3.urdf.xacro#L54-L62)

**Comment by gavanderhoorn** [comment]
Seeing as this is not really an issue with the packages in this repository, I'm inclined to close this.

Would you agree @wkentaro?

**Comment by wkentaro** [comment]
Yeah, thanks.
