### ISSUE TITLE
M-710iC axis 6 reversed

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/fanuc_experimental#27]
I'm pretty sure that the M-710iC robot definition is wrong because axis 6 is reversed.

The following RViz captures are connected to the real robot with  `ROSSTATE`

Axis 6 = 0°
===
![0_deg](https://cloud.githubusercontent.com/assets/5566160/23064805/7622352e-f512-11e6-840b-17637fed7031.jpg)
![0_deg_rviz](https://cloud.githubusercontent.com/assets/5566160/23064806/7792719e-f512-11e6-9593-5bf390069710.png)

Axis 6 = -90°
==
![-90_deg](https://cloud.githubusercontent.com/assets/5566160/23064813/7f2d6a62-f512-11e6-9007-d67af77f6439.jpg)

![-90_deg_rviz](https://cloud.githubusercontent.com/assets/5566160/23064814/81425eac-f512-11e6-9d85-979cfafded97.png)

Fetched value from `/joint_states` corresponds to the value I read on the teach pendant so the problem must be that the axis is reversed in the XACRO/URDF definition of the robot.

**Comment by VictorLamoine** [comment]
Fetched value from `/joint_states` corresponds to the value I read on the teach pendant so the problem must be that the axis is reversed in the XACRO/URDF definition of the robot.

**Comment by VictorLamoine** [comment]
This obviously does not help with the sensor calibration :smile:

**Comment by gavanderhoorn** [comment]
> This obviously does not help with the sensor calibration :smile: 

no, it certainly doesn't.

Thanks for noticing.

**Comment by gavanderhoorn** [comment]
And thanks for the fix.

Nice cell model btw.
