### ISSUE TITLE
Lrmate200id attempting to move physical robot

### ISSUE THREAD

**Issue by cvanclee** [ros-industrial/fanuc_experimental#31]
I'm trying to connect the physical lrmate200id to my computer and issue commands to it. I'm running the command 

`roslaunch fanuc_lrmate200id_moveit_config moveit_planning_execution.launch sim:=false robot_ip:=10.0.0.93` 

which results in the error

`[FATAL] [1498826383.877209818]: Parameter '~moveit_controller_manager' not specified. This is needed to identify the plugin to use for interacting with controllers. No paths can be executed.
`

As a side note, the robot state is loaded into RViz correctly, with all the joint positions matching the physical robot's state

**Comment by gavanderhoorn** [comment]
You've mentioned earlier that you've re-run the MoveIt Setup Assistant for the `fanuc_lrmate200id_moveit_config` package. It's very likely that you overwrote certain files at the end which configured the MoveIt package for use with real hardware.

This should be relatively trivial to check if you've still got things in a git repository. Just check your history.

> As a side note, the robot state is loaded into RViz correctly, with all the joint positions matching the physical robot's state

that makes sense, as that is the responsibility of `fanuc_driver`, which gets started by `moveit_planning_execution.launch`, which isn't touched by the MSA.

**Comment by cvanclee** [comment]
Yup, fanuc_lrmate200id_moveit_controller_manager.launch.xml was empty. I should have noticed that before. Thank you!

**Comment by gavanderhoorn** [comment]
Could you please close the issue if you feel it has been resolved?
