### ISSUE TITLE
Collision meshes of LR 200id too restrictive.

### ISSUE THREAD

**Issue by jettan** [ros-industrial/fanuc_experimental#34]
The current collision meshes of the LR mate 200id are too restrictive.
In particular, I'm talking about the mesh for link2.
Link 2 is supposed to have a bigger opening such that link 4 is partly inside of the current link 2 collision mesh (example of such a joint configuration in radians: [0, 0.3, -1, 0, 1.3, 0]).

**Comment by gavanderhoorn** [comment]
Take a look at ros-industrial/kuka_experimental#59, which is basically the same problem, but for KUKA Agilus KR6 and KR10.

See ros-industrial/kuka_experimental#76 for a PR that addressed that issue.

You could probably improve the collision mesh for `link_2` using the `bounding_mesh` tool mentioned in the PR.

**Comment by jettan** [comment]
Thanks, I managed to get the bounding_mesh tool to work. Will make a PR after I tested tomorrow whether the bounded mesh of link2 works and/or whether I need to also change link3/4.

**Comment by gavanderhoorn** [comment]
@jettan: did your collision meshes work better?

**Comment by jettan** [comment]
Yes it did, but I am hesitant to make a PR because it might be too lax (or the robot I am working with isn't mastered very accurate). The only replacement I needed in collision mesh was as you suggested link_2.
