### ISSUE TITLE
lrmate200id Motion Planning issues

### ISSUE THREAD

**Issue by jav-solo** [ros-industrial/fanuc_experimental#38]
I am having issues with moving my fanuc lrmate 200id with code. I can use the gui in rviz and move the six axis ball which gives me the coordinates and orientation. If i then put those same exact coordinates to compute a Cartesian path. I get multiple errors and warnings. 

```
[ WARN] [1527256660.896593985]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000141 seconds
[ERROR] [1527256660.896706601]: manipulator[RRTConnectkConfigDefault]: Insufficient states in sampleable goal region
[ERROR] [1527256660.896736589]: manipulator[RRTConnectkConfigDefault]: Insufficient states in sampleable goal region
[ERROR] [1527256660.896770195]: manipulator[RRTConnectkConfigDefault]: Insufficient states in sampleable goal region
[ERROR] [1527256660.896804013]: manipulator[RRTConnectkConfigDefault]: Insufficient states in sampleable goal region
[ WARN] [1527256660.896847235]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000149 seconds
[ INFO] [1527256660.896914156]: Unable to solve the planning problem
```

A few observations I've made, the planner seems to take a longer path when using RViz, and it tries to plan to a shorter path with the Cartesian path plan.

**Comment by gavanderhoorn** [comment]
I don't think I have enough information to help you.

Are you using any particular setup? Just the plain `lrmate200id` robot in empty space? Something else?

I can only think of one thing to check for now: do you run into the same error with another robot model?

**Comment by jav-solo** [comment]
No I’ve added a collision in the xacro that represents the table that the current robot is on. 

I have not tried to use it with any other robot models. 

Some observations I’ve made: 
When I use RViz to motion plan and I select random valid, it gives me invalid poses all the time and it gives me the same warning and errors, just not quite as many. 

I am using the IKFast plugin and RRTConnect as my default solver and planner.

**Comment by gavanderhoorn** [comment]
@javiersolorzano wrote:
> No I’ve added a collision in the xacro that represents the table that the current robot is on.

I think it would help if you could show me how you did that (ie: upload your package to github or a gist).

> When I use RViz to motion plan and I select random valid, it gives me invalid poses all the time and it gives me the same warning and errors, just not quite as many.

This could be a faulty setup of your xacro / environment modelling. Is the robot colliding with the geometry you added? It sounds like something is seriously wrong.

**Comment by jav-solo** [comment]
@gavanderhoorn 

```xml
<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find fanuc_resources)/urdf/common_materials.xacro"/>

  <xacro:macro name="fanuc_lrmate200id" params="prefix">
    <!-- links: main serial chain -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/visual/base_link.stl"/>
        </geometry>
        <xacro:material_fanuc_gray28 />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/collision/base_link.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/visual/link_1.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/collision/link_1.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_2">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/visual/link_2.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/collision/link_2.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_3">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/visual/link_3.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/collision/link_3.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_4">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/visual/link_4.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/collision/link_4.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_5">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/visual/link_5.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/collision/link_5.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_6">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/visual/link_6.stl"/>
        </geometry>
        <xacro:material_fanuc_black />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_lrmate200id_support/meshes/lrmate200id/collision/link_6.stl"/>
        </geometry>
      </collision>
    </link>

    <link name ="table">
      <visual>
        <geometry>
          <box size="1.2 0.89 0.013"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="1.2 0.89 0.013"/>
        </geometry>
      </collision>
    </link>

    <!-- joints: main serial chain -->
    <joint name="${prefix}joint_1" type="revolute">
      <origin xyz="0 0 0.330" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}link_1" />
      <axis xyz="0 0 1" />
      <limit effort="0" lower="-2.965" upper="2.965" velocity="7.85" />
    </joint>
    <joint name="${prefix}joint_2" type="revolute">
      <origin xyz="0.050 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_1" />
      <child link="${prefix}link_2" />
      <axis xyz="0 1 0" />
      <limit effort="0" lower="-1.745329" upper="2.530727" velocity="6.63" />
    </joint>
    <joint name="${prefix}joint_3" type="revolute">
      <origin xyz="0 0 0.330" rpy="0 0 0"/>
      <parent link="${prefix}link_2" />
      <child link="${prefix}link_3" />
      <axis xyz="0 -1 0" />
      <limit effort="0" lower="-2.450966" upper="4.886922" velocity="9.08" />
    </joint>
    <joint name="${prefix}joint_4" type="revolute">
      <origin xyz="0 0 0.035" rpy="0 0 0"/>
      <parent link="${prefix}link_3"/>
      <child link="${prefix}link_4"/>
      <axis xyz="-1 0 0"/>
      <limit effort="0" lower="-3.315" upper="3.315" velocity="9.60" />
    </joint>
    <joint name="${prefix}joint_5" type="revolute">
      <origin xyz="0.335 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_4"/>
      <child link="${prefix}link_5"/>
      <axis xyz="0 -1 0"/>
      <limit effort="0" lower="-2.18" upper="2.18" velocity="9.51" />
    </joint>
    <joint name="${prefix}joint_6" type="revolute">
      <origin xyz="0.080 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_5"/>
      <child link="${prefix}link_6"/>
      <axis xyz="-1 0 0"/>
      <limit effort="0" lower="-6.285" upper="6.285" velocity="17.45" />
    </joint>

    <!-- ROS-Industrial 'base' frame: base_link to Fanuc World Coordinates transform -->
    <link name="${prefix}base" />
    <joint name="${prefix}base_link-base" type="fixed">
      <origin xyz="0 0 0.330" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- ROS-Industrial 'flange' frame: attachment point for EEF models -->
    <link name="${prefix}flange" />
    <joint name="${prefix}joint_6-flange" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}link_6" />
      <child link="${prefix}flange" />
    </joint>

    <!-- ROS-Industrial 'tool0' frame: all-zeros tool frame -->
    <link name="${prefix}tool0" />
    <joint name="${prefix}link_6-tool0" type="fixed">
      <origin xyz="0 0 0" rpy="${pi} ${-pi/2.0} 0" />
      <parent link="${prefix}link_6" />
      <child link="${prefix}tool0" />
    </joint>

    <!--Table joining the robot base -->
    <joint name="table_to_robot" type="fixed">
      <parent link="base_link"/>
      <child link="table"/>
      <origin xyz="0.33 0 0" rpy="0 0 0"/>
    </joint>	

  </xacro:macro>
</robot>
```

This is all that I changed in the macro.

More often than the table the robot is also in self collision which prevents planning.

**Comment by gavanderhoorn** [comment]
Two comments:

 1. it shouldn't matter, but I'd recommend to create a separate "work cell" xacro/urdf in which you combine your table and the robot model. Don't put work cell models into the base robot xacro macro. It's not very nice and reduces reusability of the robot macro.
 1. it seems strange (but again, might not be important) that the robot `base_link` is the `parent` of the `table`. I'd expect that to be the other way around.

At this point I'd suggest to remove your table from the robot macro and check whether you run into the same issues.

**Comment by jav-solo** [comment]
Well, I had made the table the parent link but would get a warning and sometimes an error because it did not  match the the base frame in the Moveit! config. Also, I remember trying to remove the table and observed that it still had the same issues as before. 

I will try to remove it and see again. Would there be any other reason? I will move the actual robot to specific coordinates I read from RViz and then input them into my code and it gives me that error. Also, I have noticed that it actually will visualize the plan but often contains instantaneous rotations of some joints, particularly joint 1-2. Why would the same planner be planning a longer distance with the GUI and a shorter one with the code?

**Comment by jav-solo** [comment]
I removed the table and now the random valid seems to work. How can I add the table without affecting the collision awareness of the robot?

Also, moving via code still was unsuccessful. This time I tried using geometry_msgs::Pose to move it to a known possible position and I received this error:

```
Error:   RRTConnect: Unable to sample any valid states for goal tree
         at line 215 in /tmp/binarydeb/ros-kinetic-ompl-1.2.3/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp
```

**Comment by gavanderhoorn** [comment]
@javiersolorzano wrote:
> I removed the table and now the random valid seems to work. How can I add the table without affecting the collision awareness of the robot?

Did you re-run the MoveIt Setup Assistant after adding the new geometry? If you didn't, the allowed collision matrix would not be updated.

I can see if I can reproduce your issue later today, but that may take while. In general I have the idea that something is out of sync or not updated properly and then leads to MoveIt/OMPL not being correctly setup, leading to your issues.

re: code vs rviz plugin difference: that is really hard to answer without seeing your code. There are so many things that influence MoveIt motion plan requests.

**Comment by gavanderhoorn** [comment]
But in general my advice would still be to create a separate work cell xacro macro, `include` the robot macro file, instantiate it and add the table there. Consider the robot xacro as read-only.

You also cannot change the kinematic chain, or you'll run into things like #30. That is a consequence of how IKFast plugins work.

**Comment by jav-solo** [comment]
@gavanderhoorn wrote:

>Did you re-run the MoveIt Setup Assistant after adding the new geometry? If you didn't, the allowed collision matrix would not be updated.

No, I did not ever run it with the table which now make a lot of sense as to why it would be in collision.

@gavanderhoorn wrote:

>re: code vs rviz plugin difference: that is really hard to answer without seeing your code. There are so many things that influence MoveIt motion plan requests.

I have only tried to move the robot similar to the ways done in the Moveit! tutorials. (using positions and orientations that I know are within the limits of the robot) Example:
`
geometry_msgs::Pose target_pose1;
target_pose1.orientation.w = 1.0; 
target_pose1.position.x = 0.28; 
target_pose1.position.y = -0.2; 
target_pose1.position.z = 0.5; 
move_group.setPoseTarget(target_pose1); 
move_group.move(); `

@gavanderhoorn wrote:

>You also cannot change the kinematic chain, or you'll run into things like #30. That is a consequence of how IKFast plugins work.

I have not modified the kinematic chain at all.

Just to be clear, you recommend the following steps should be taken;

1. Create a new xacro using the robot macro file as read only.
2. Run MoveIt! Setup Assistant when I have created that new xacro auto-generating the self collision matrix.

3. Retest

In regards to adding the table, should I make the base-link the table in the Setup Assistant to prevent the incorrect parent link error?

**Comment by jav-solo** [comment]
@gavanderhoorn 

I reran the setup assistant and it seemed top eliminate the random valid option. I will continue testing with the actual robot this week and let you know if I run into more issues. Thanks!

**Comment by gavanderhoorn** [comment]
Ok, good to hear that got cleared up.

I'm closing this for now, as I don't expect the fact that you're going to use a real robot is going to influence things very much.

If you encounter the same issue, please re-open.

**Comment by jav-solo** [comment]
@gavanderhoorn 

Thanks for your help, I just tested it out on the actual robot and everything seems resolved. I do have one more question, I have turned the speed all the way up on the robot to 100% via the Karel variables. Is there something else I can do/check to increase the speed? Also does the kinematics solver or the planner increase the velocity of the planned path?

**Comment by gavanderhoorn** [comment]
>  Is there something else I can do/check to increase the speed?

No, most likely not. Fanuc robots are extremely limited in the ways they can be controlled externally, and the driver uses one particular approach that does not result in very good motion performance. You could see whether [fanuc_driver_exp](https://github.com/gavanderhoorn/fanuc_driver_exp) performs any better for you (if you're not already using it), but I don't expect it.

gavanderhoorn/fanuc_driver_exp#12 may be of interest, but is not a full ROS-I driver at the moment.

> Also does the kinematics solver or the planner increase the velocity of the planned path?

I don't understand this.

**Comment by gavanderhoorn** [comment]
Another thing to keep in mind is that industrial controllers don't do very well with dense trajectories. That is also true when executing motions using hard-coded, off-line generated programs (ie: TP programs for Fanuc).

Sparser trajectories generally work better and will result in faster motion.

**Comment by jav-solo** [comment]
Everything is working fine, thank you for your help!
