### ISSUE TITLE
What is the precision for control of end effector ?

### ISSUE THREAD

**Issue by jediofgever** [ros-industrial/fanuc_experimental#49]
Hi,
This is more a question than an issue, 
when I set a goal pose for end-effector, the robot  cannot be at the goal in precision manufacturer promises. For instance in below picture;

![Screenshot from 2019-09-23 18-25-59](https://user-images.githubusercontent.com/18460336/65399080-4ec48380-dded-11e9-9843-d1878e2912f0.png)
I set goal pose for end effector as ;
```
robot_x; 400.0
robot_y; 0.0
robot_z; 700.0
robot_rx; 180.0
robot_ry; 0.0
robot_rz; 0.0
```
However the end effector ends up at ;
```
robot_x; 400.085405
robot_y; 0.042173
robot_z; 699.966790
robot_rx; 179.953275
robot_ry; 0.008988
robot_rz; -0.021190
```
is this expected behavior? if not what could be possible reasons for this behavior ?  
According to manufacturer's claim the precision is 3 decimals.

**Comment by jediofgever** [comment]
Sorry,  not really related to this repository, I tested robot with a simple TP program even in there robot seems to suffer to be precise on 3 decimals

**Comment by gavanderhoorn** [comment]
> According to manufacturer's claim the precision is 3 decimals.

There are many factors that affect the behaviour and performance of the robot here, two of which I would like to draw your attention to:

 1. accuracy vs repeatability: Fanuc (and almost all other robot mfgs) spec *repeatability*, not accuracy. You are asking the robot to move its TCP to a specific Cartesian pose, which is a task that requires accuracy. This can be done, but would require calibrating your robot.

    Now if the robot would not end up at the same pose after you make it go somewhere else (so `A -> B -> A`), then repeatability specs would not be met and you'd have reason to 'complain'.

    As far as I can tell -- from the limited information you provide -- it could well be that the robot is performing exactly as it should.

 1. ROS' FK vs robot's FK: the urdf on the ROS side is used for visualisation tasks, but also for collision avoidance path planning in MoveIt *and* for performing FK based on joint angles published by the driver. The urdf you created modelled an *ideal robot*, based on data from the datasheets.

     No robot is ever ideal, so there is a good chance that the results from FK on the ROS side show slight differences with those the robot's controller will report. This is not just due to calibration of link lengths and joint origins, but also (for larger robots and heavier payloads) due to link deflection compensation and other dynamic effects.

     Similar to the previous point: it could well be that the robot is performing perfectly fine, but your expectations are not completely aligned with what a real robot would do here.

**Comment by jediofgever** [comment]
Your two points made me to have a better understanding of situation.

 In my application the robot is not supposed to perform repetitive tasks but more like perception based tasks which could lead robot's TCP to different poses each time, therefore I was seeking for the accuracy that asked in the description of issue. However the calibration step seems what I am looking for in this case.

Thank you for the clarification
