### ISSUE TITLE
Import R-2000iC/125L variant from isys-vision

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc_experimental#60]
@marip8: you have files for the `125L` variant in your fork in the `model/r2000ic` branch.

Would you be willing to merge those with the `fanuc_r2000ic_support` package in this repository?

I'd be mostly interested in the current state, not so much the complete commit history (to avoid repository bloat).

**Comment by gavanderhoorn** [comment]
Is 9146b71e correct btw? Afaik, the default toolframe on R-2000iC/125Ls is the same as for other Fanucs.

**Comment by marip8** [comment]
> @marip8: you have files for the 125L variant in your fork in the model/r2000ic branch.
>
> Would you be willing to merge those with the fanuc_r2000ic_support package in this repository?

Sure. I have the CAD models, but I haven't had a chance to convert them into mesh files yet. I'll see if I can do that this week. I think the URDF and associated launch/config files should be complete though.

> Is 9146b71 correct btw? Afaik, the default toolframe on R-2000iC/125Ls is the same as for other Fanucs.

I'm not sure. I haven't tested this on a real robot. If my URDF is different than the others in the R2000 package, I'll change it to be like existing ones until someone can try it out on hardware.

**Comment by gavanderhoorn** [comment]
Ah, I now see I got confused.

I thought [marip8/fanuc_experimental/fanuc_r2000ic_support](https://github.com/marip8/fanuc_experimental/tree/d4a0e276c89f8780dcb4005ac23608c9348d4d9b/fanuc_r2000ic_support) contained the `125L` changes, but it's actually a version of the `165F`.

We already have the `165F` here, but it would indeed be great to merge the `125L`.

**Comment by gavanderhoorn** [comment]
It looks like [isys-vision/fanuc_experimental](https://github.com/isys-vision/fanuc_experimental/tree/4ceb4c25b292363d593346ef2e7e229d432ab500) contains a version of the `125L` already (but with the wrong scale).

And a version of the `165F`.

@timobkt seems to have pushed (very) detailed meshes though. I'm not sure that was the intention.

@simonschmeisser: would you guys be willing to contribute the `125L`?

**Comment by simonschmeisser** [comment]
sure! I'll do an internal review with Timo and then we can open a PR. The `165F` is actually the one you merged earlier, I think he just copy pasted the folder instead of your commit.

By "detailed meshes" you're probably referring to the somewhat unclear licensing of the meshes mailed from Fanuc? We'll push the convex hull as it's custom here

**Comment by gavanderhoorn** [comment]
> sure! I'll do an internal review with Timo and then we can open a PR. The `165F` is actually the one you merged earlier, I think he just copy pasted the folder instead of your commit.

Ah, ok.

> By "detailed meshes" you're probably referring to the somewhat unclear licensing of the meshes mailed from Fanuc?

Yes.

Afaik making those available publicly is still not something they like us to do.

I'm starting to consider ignoring this though, and might release detailed models of all supported variants sometime in the future.

> We'll push the convex hull as it's custom here

thanks

**Comment by gavanderhoorn** [comment]
Changed the title of the issue as I believe @simonschmeisser and @timobkt have a version of the `125L` xacro already with meshes in their fork, while @marip8 would still need to convert all the meshes.

Seems like it would be less work for @simonschmeisser and @timobkt :)

**Comment by gavanderhoorn** [comment]
Ping @simonschmeisser @timobkt?
