### ISSUE TITLE
Fanuc URDF transmission tags for gazebo

### ISSUE THREAD

**Issue by akashjinandra** [ros-industrial/fanuc_experimental#64]
Hello is it possible to add the transmission files in the urdf to allow ROS Control to function correctly in gazebo. I know alot of the open PR regarding gazebo did not pass, so is there any push to allow for that.

**Comment by gavanderhoorn** [comment]
I'm not really a fan of adding Gazebo specific elements to the base URDFs.

In the PR you reference (I believe that would be #20), those elements are added by a wrapper `xacro:macro` which is hosted by a special `_gazebo` package.

We could add such a `_gazebo` package for the model you're interested in.

> I know alot of the open PR regarding gazebo did not pass, so is there any push to allow for that.

See the later comments on #21 fi.

**Comment by gavanderhoorn** [comment]
I'm going to close this due to inactivity.

@akashjinandra: if you'd be interested in addressing this, please comment and we can re-open.

**Comment by gavanderhoorn** [comment]
There appears to be some development in https://github.com/ros-industrial/fanuc_experimental/compare/kinetic-devel...BastianSolutionsRandD:200_id7l_gazebo.

It looks like this follows the approach taken in the old `ur_gazebo` package.

From a dependency management perspective, it would be better to *not* modify the base `_macro.xacro`s. Have you considered the wrapper `_gazebo` package?
