### ISSUE TITLE
fanuc_m10ia_moveit_config has not existing dependency

### ISSUE THREAD

**Issue by dirk-thomas** [ros-industrial/fanuc_experimental#7]
The CI job http://jenkins.ros.org/job/devel-hydro-fanuc_experimental/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/3/console fails because of the missing dependency on `fanuc_m10ia_support`.

**Comment by gavanderhoorn** [comment]
The package `fanuc_m10ia_support` is part of the `fanuc` repository. So it isn't in the same repository, but it does exist. AFAIU I cannot express that dependency in a devel job, am I wrong?

**Comment by dirk-thomas** [comment]
If the `fanuc` repository is not released it is not possible to run integration tests for packages depending on it since all dependencies must be installable from Debian.

If you don't plan to release the dependencies from the `fanuc` repository in the near future it would probably be best to remove the `fanuc_experimental` repository from the CI farm since it will always fail.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, we are pretty close to a release, but if you want I can add a fanuc specifc job to the ros-i jenkins build server.

**Comment by dirk-thomas** [comment]
It's ok if you are going to release it sometime in the future. We just try to either get the jobs working or ditch them from the farm.

**Comment by gavanderhoorn** [comment]
@dirk-thomas: we are going to release the `fanuc` package, but I think I'll disable the CI builds for `fanuc_experimental` for now. We can do them on the ROS-I jenkins server.

**Comment by dirk-thomas** [comment]
As you wish.

**Comment by gavanderhoorn** [comment]
Closing. See #8.

Will re-enable as soon as `fanuc` has been released.
